const codes = {
    DEFAULT_ERROR_CODE: 'GENERIC',
    DEFAULT_ERROR_STATUS_CODE: 500,
    USER_ERROR_STATUS_CODE: 400,
    UNPROCESSED_ENTITY: 'UNPROCESSED_ENTITY',
    ERROR_NOT_FOUND: 'NOT_FOUND',
    ERROR_TECHNICAL: 'TECHNICAL',
    ERROR_USER_NOT_FOUND: 'USER_NOT_FOUND',
    DEFAULT_SUCCESS_STATUS_CODE: 200,
    USER_EXIST: 'USER_EXIST',
    ERROR_WRONG_CREDENTIALS: 'ERROR_WRONG_CREDENTIALS',
    ERROR_MISSING_TOKEN: 'ERROR_MISSING_TOKEN',
    ERROR_INVALID_TOKEN: 'ERROR_INVALID_TOKEN'
};

export { codes };
